server:
  port: 8070

spring:
  config:
    import:
      - classpath:application-infrastructure-jpa.yml

  # HTTP 인코딩 설정
  web:
    resources:
      add-mappings: true

  # Thymeleaf 인코딩 설정
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
